### ISSUE TITLE
Flux not able to decrypt in Git File 

### ISSUE THREAD

**Issue by Rahulsharma0810** [MathiasPius/kronform#133]
Thanks for the Awesome writeup Mathias, Perhaps the guide is outdated compared to the current repo content.

I am trying to use age instead pgp and getting below issues

Error

```
pull-secrets	main@sha1:8f4690b0	False	False	decryption failed for 'docker-hub-pull-secret': failed to decrypt and format 'default/docker-hub-pull-secret' Secret data: cannot get sops data key: Failed to get the data key required to decrypt the SOPS file.

            	                  	     	     	Group 0: FAILED
            	                  	     	     	  age1g9f5g9a02tc60zhqezv3uhkup6g309ygnpk7k8yf8hys48gcw5zqghf0zxxx: FAILED
            	                  	     	     	    - | failed to load age identities: failed to open file: open
            	                  	     	     	      | /.config/sops/age/keys.txt: no such file or directory

            	                  	     	     	Recovery failed because no master key was able to decrypt the file. In
            	                  	     	     	order for SOPS to recover the file, at least one key has to be successful,
            	                  	     	     	but none were.
```

Cross checked `age.key` with secrets in k8s

```
kubectl get secret sops-age -n flux-system -o jsonpath="{.data['age\.key']}" | base64 --decode
```

Both matched 100%. Perhaps, as well as secret file.

```
#.manifests/infrastructure/pull-secrets/docker-hub.yaml
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
      - recipient: age1g9f5g9a02tc60zhqezv3uhkup6g309ygnpk7k8yf8hys48gcw5zqghf0zxxx
```

Key also matched, Not Sure what is the error in config.
