### ISSUE TITLE
PVC creation errors

### ISSUE THREAD

**Issue by MichaelKora** [MathiasPius/kronform#3]
when i create a PVC it is pending..looking in the logs of the provisioner shows
`pvc-68745313-91b4-4c06-8f22-c8c95faa4833 GRPC error: rpc error: code = Aborted desc = an operation with the given Volume ID pvc-68745313-91b4-4c06-8f22-c8c95faa4833 already exists `

But the `PVC` cleary did not exist..
@MathiasPius  any ideas where the error can lie?

**Comment by MichaelKora** [comment]
also creating a PV manually and binding it to the PVC works..but its not optimal

**Comment by MathiasPius** [comment]
Ah sorry didn't see you replied to the old issue. Is the ceph cluster in a healthy state?

Easiest way to check is probably through the [dashboard](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-dashboard/#visualization-of-physical-disks-section-in-the-dashboard)

Might be some relevant troubleshooting tips here: https://github.com/rook/rook/issues/7756

**Comment by MichaelKora** [comment]
ok will go through the materials..and will let you know how it went. thanks

**Comment by MichaelKora** [comment]
@MathiasPius  So i got the cephcluster to run and to be in an healthy state..i am using pretty much the same configs as you..but the ods pods are not deployed... they are not scheduled at all. also the `CephCluster` object shows following warning: ` User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot create resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"`...it added a clusterrole and bound it to the named SA but this didnt fix the issue...(i dont if both behaviors are connected)

**Comment by MichaelKora** [comment]
also i ended up using the helm chart to install the operators since i was getting these errors
`helmrepository`: ` Warning  Failed  64s   source-controller  failed to fetch Helm repository index: failed to cache index to temporary file: Get "https://charts.rook.io/release/index.yaml": dial tcp 18.239.69.97:443: i/o timeout`

`helm-release`: `HelmChart 'rook-ceph/rook-ceph-rook-ceph' is not ready: latest generation of object has not been reconciled`

**Comment by MichaelKora** [comment]
here my `.yaml`

```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: rook-release
  namespace: rook-ceph
spec:
  interval: 5m0s
  url: https://charts.rook.io/release
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: ">=v1.13.0 <v1.14.0"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: rook-ceph
      interval: 1m
  values:
    crds:
      enabled: true
    enableDiscoveryDaemon: true

```

**Comment by MichaelKora** [comment]
> @MathiasPius So i got the cephcluster to run and to be in an healthy state..i am using pretty much the same configs as you..but the `OSDs` pods are not deployed... they are not scheduled at all. also the `CephCluster` object shows following warning: ` User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot create resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"`...it added a clusterrole and bound it to the named SA but this didnt fix the issue...(i dont if both behaviors are connected)

@MathiasPius 

```
kg cephcluster -n rook-ceph
NAME                    DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH        EXTERNAL   FSID
its-rook-ceph-cluster   /var/lib/rook     3          25m   Ready   Cluster created successfully   HEALTH_WARN              1afd497a
```

**Comment by MathiasPius** [comment]
What do the logs of the discovery pods say? Rook should spawn discovery pods on each node to determine which of the drives are available for use as OSDs

**Comment by MichaelKora** [comment]
What's the discovery pods name ? Am not seeing any 🤔

**Comment by MathiasPius** [comment]
> > @MathiasPius So i got the cephcluster to run and to be in an healthy state..i am using pretty much the same configs as you..but the `OSDs` pods are not deployed... they are not scheduled at all. also the `CephCluster` object shows following warning: ` User "system:serviceaccount:rook-ceph:rook-ceph-system" cannot create resource "servicemonitors" in API group "monitoring.coreos.com" in the namespace "rook-ceph"`...it added a clusterrole and bound it to the named SA but this didnt fix the issue...(i dont if both behaviors are connected)
> 
> @MathiasPius
> 
> ```
> kg cephcluster -n rook-ceph
> NAME                    DATADIRHOSTPATH   MONCOUNT   AGE   PHASE   MESSAGE                        HEALTH        EXTERNAL   FSID
> its-rook-ceph-cluster   /var/lib/rook     3          25m   Ready   Cluster created successfully   HEALTH_WARN              1afd497a
> ```

This seems unrelated to the issue of provisioning OSDs, but looks like the issue is mentioned [here](https://github.com/rook/rook/issues/13702) pointing to [this documentation](https://rook.io/docs/rook/latest/Storage-Configuration/Monitoring/ceph-monitoring/#prometheus-consoles)

**Comment by MichaelKora** [comment]
> In my cluster they're called:
> 
> ```
> 
> rook-ceph-osd-prepare-n1-db27h                  0/1     Completed   0             7d22h
> 
> rook-ceph-osd-prepare-n2-tfmvl                  0/1     Completed   0             7d22h
> 
> rook-ceph-osd-prepare-n3-4kxjk                  0/1     Completed   0             7d22h
> 
> ```
> 
> Where the n1-3 are the node names.

I don't have them running  in my cluster. That's what I don't understand🫤

**Comment by MathiasPius** [comment]
Try grepping for `prepare` in the operator pod's logs. In mine it shows:
```
2024-04-03 20:28:14.360120 I | op-k8sutil: Removing previous job rook-ceph-osd-prepare-n1 to start a new one
2024-04-03 20:28:14.375938 I | op-k8sutil: batch job rook-ceph-osd-prepare-n1 still exists
2024-04-03 20:28:17.381855 I | op-k8sutil: batch job rook-ceph-osd-prepare-n1 deleted
2024-04-03 20:28:17.563265 I | op-k8sutil: Removing previous job rook-ceph-osd-prepare-n2 to start a new one
2024-04-03 20:28:17.583691 I | op-k8sutil: batch job rook-ceph-osd-prepare-n2 still exists
2024-04-03 20:28:20.587999 I | op-k8sutil: batch job rook-ceph-osd-prepare-n2 deleted
2024-04-03 20:28:21.355654 I | op-k8sutil: Removing previous job rook-ceph-osd-prepare-n3 to start a new one
2024-04-03 20:28:21.368702 I | op-k8sutil: batch job rook-ceph-osd-prepare-n3 still exists
2024-04-03 20:28:24.374258 I | op-k8sutil: batch job rook-ceph-osd-prepare-n3 deleted
```

**Comment by MichaelKora** [comment]
```
~$ k logs rook-ceph-operator-54d8747b6d-67fxt -n rook-ceph | grep prepare

~$

```

no lines about prepare..somehow the operator doesnt even try to deploy OSDs...as if i disabled it...

**Comment by MichaelKora** [comment]
```
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: my-rook-ceph-cluster
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.2
    allowUnsupported: false
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
      - name: rook
        enabled: true
    count: 2
    allowMultiplePerNode: false
  dashboard:
    enabled: true

  removeOSDsIfOutAndSafeToRemove: false
  storage:
    config:
    onlyApplyOSDPlacement: true
    useAllDevices: true
    useAllNodes: false
    nodes:
      - name: "vm-1"
        resources:
          limits:
            cpu: "2"
            memory: "4096Mi"
          requests:
            cpu: "1"
            memory: "2048Mi"

      - name: "vm-2"
        resources:
          limits:
            cpu: "2"
            memory: "4096Mi"
          requests:
            cpu: "1"
            memory: "2048Mi"

      - name: "vm-3"
        resources:
          limits:
            cpu: "2"
            memory: "4096Mi"
          requests:
            cpu: "1"
            memory: "2048Mi"
  placement:
    all:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  cephConfig:
    global:
      osd_pool_default_size: "3"
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
    pgHealthCheckTimeout: 0
  monitoring:
    enabled: true
    metricsDisabled: false
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
    startupProbe:
      mon:
        disabled: false
      mgr:
        disabled: false
      osd:
        disabled: false
```
